// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"database/sql"
)

type ApiKey struct {
	KeyID  int64
	ApiKey string
	UserID int64
}

type Task struct {
	TaskID      int64
	Title       string
	Description sql.NullString
	Completed   sql.NullBool
	CreatedBy   int64
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type User struct {
	UserID   int64
	Username string
}
